[package]
name = "tournament-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
rand = "0.8"
csv = "1.2"
log = "0.4"
simplelog = "0.12"
